# Generated by Django 6.1 on 2026-08-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_edicao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
