# Generated by Django 6.1 on 2026-08-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_tarefa_data_edicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_edicao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
